services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: groceries
      POSTGRES_USER_FILE: /run/secrets/db_user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/
    secrets:
      - db_password
      - db_user
secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt
volumes:
  pgdata: