services:
  groceries-web-app:
    image: openjdk:17
    container_name: groceries-app
    working_dir: /app
    volumes:
      - ./target/groceries-0.0.1-SNAPSHOT.jar:/app/groceries-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/groceries
    depends_on:
      - db
    command: ["java", "-jar", "groceries-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: groceries
      POSTGRES_USER_FILE: /run/secrets/db_user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/
    secrets:
      - db_password
      - db_user
secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt
volumes:
  pgdata: